Page header.mag 3055
excelWithBusiness/TS-Filtered-SC-Components pull request #49
Opened 2020-11-30 13:46 UTC by philjonasfiltered

# <JIRA issue / Title>

## TL;DR

-   List
-   The
-   Core
-   Changes

## Details

Checklist / Reminders:

-   [ ] Documentation / Story is created / adapted
-   [ ] Unit tests
-   [ ] CSS changes are BEM-compliant

2020-11-30 16:40 UTC, tricaalexandru approved these changes

2020-11-30 16:40 UTC, tricaalexandru commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  width?: string
@philjonasfiltered what is the question mark for?

2020-11-30 16:51 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  width?: string
@tricaalexandru it makes the property optional, so it can be passed in or not.

2020-11-30 16:58 UTC, matthill8286 requested changes

2020-11-30 16:58 UTC, matthill8286 commented on src/components/Organisms/PageHeader/PageHeader.story.tsx
> +        onClick={function noRefCheck() {}}
you can use jest.fn() for mocks

2020-11-30 16:58 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  width?: string
shouldn't be setting a width, the grid controls the width 😄

2020-11-30 16:58 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  width?: string
@philjonasfiltered shouldn't be setting a width, the grid controls the width 😄  @tricaalexandru it's an optional type

2020-11-30 16:58 UTC, matthill8286 commented on src/components/Organisms/PageHeader/PageHeader.tsx
> +    </div>
@philjonasfiltered Could you use a grid system and flex-box to control the layout, as it will help on other device sizes. Really the components fill 100% of their parent Grid container.

2020-11-30 17:02 UTC, matthill8286 requested changes

2020-11-30 17:02 UTC, matthill8286 commented on src/components/Organisms/PageHeader/PageHeader.tsx
> +      <Divider color="primary" height={undefined} />
@philjonasfiltered no need for undefined here as it's an optional prop, it'll just default to a specific height.

2020-11-30 17:02 UTC, matthill8286 commented on src/components/Organisms/PageHeader/PageHeader.tsx
> +}) => {
@philjonasfiltered What does this return?? Would be nice to see it...
```suggestion
}): JSX.Element => {
```

2020-11-30 17:07 UTC, philjonasfiltered commented on src/components/Organisms/PageHeader/PageHeader.story.tsx
> +        onClick={function noRefCheck() {}}
and you just mentioned it this morning 🤣 Updated it

2020-12-01 10:37 UTC, matthill8286 approved these changes

2020-12-01 10:37 UTC, matthill8286 commented on src/components/Organisms/PageHeader/PageHeader.interface.ts
> +  to?: H.LocationDescriptor
The type exists in the react router types

2020-12-01 11:38 UTC, merged