feat(onboarding ui): [MAG-3099] asset page footer
excelWithBusiness/TS-Filtered-SC-Components pull request #54
Opened 2020-12-02 11:23 UTC by eTheMan80

# <MAG-3099 / Asset page footer>

## TL;DR

-   Add Asset page footer
-  
-  
-  

## Details

Checklist / Reminders:

-   [X] Documentation / Story is created / adapted
-   [ ] Unit tests
-   [ ] CSS changes are BEM-compliant

2020-12-02 11:38 UTC, tricaalexandru commented
@eTheMan80 from the screenshot it seems the items are a bit condesed (that might stretch out properly with a a good resolution, but just want to double check. https://projects.invisionapp.com/share/BUZB2DJGXCW#/screens/436592929

2020-12-02 11:58 UTC, matthill8286 requested changes

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +import * as H from 'history'
@eTheMan80 This isn't used

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
`interface Link { url: string; icon: string; text: string }`

```suggestion
  links?: Link[]
```

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +    <div>
@eTheMan80 use a fragment if this is just for structure only.

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +}) => {
@eTheMan80 What does this function return?? Add a typescript return type

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +              <Cell key={index} colsLg={1} colsMd={2} colsSm={1} justify="center" align="middle">
```suggestion
              <Cell key={index} columns={1} justify="center" align="middle">
```

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +            <Picture src={logoUrl} alt="company logo" width="120px" onClick={onLogoClick} />
@eTheMan80 whats the height of the logo?

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/index.ts
> +export * from './AssetPageFooter'
@eTheMan80 Can you add a newline at the end of the file.

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.story.tsx
> +    icon: '',
@eTheMan80 Where is the icon used?? If it's not in the designs can you please remove it.

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.test.tsx
> +            icon: '',
@eTheMan80 Same here, if icon isn't in the designs, please remove it.

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +          {links &&
```suggestion
          {links ?
```

2020-12-02 11:58 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +            ))}
```suggestion
            )) : null}
```

2020-12-02 11:59 UTC, philjonasfiltered commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
perhaps you could define or import an interface for this `{ url: string; icon: string; text: string }`

2020-12-02 11:59 UTC, philjonasfiltered commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +    <div>
could `Grid` be the top component instead of `div`?

2020-12-02 12:04 UTC, eTheMan80 commented
> @eTheMan80 from the screenshot it seems the items are a bit condesed (that might stretch out properly with a a good resolution, but just want to double check. https://projects.invisionapp.com/share/BUZB2DJGXCW#/screens/436592929

@tricaalexandru the space in the window for storybook is a lot less than the one for the platform so the items will stretch out.

2020-12-02 12:06 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
@matthill8286 are you saying that I should extend the `Link` interface?

2020-12-02 12:13 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +            <Picture src={logoUrl} alt="company logo" width="120px" onClick={onLogoClick} />
@matthill8286 I'm not sure what the height of the logo will be, it would be different for each client.

2020-12-02 12:15 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.story.tsx
> +    icon: '',
@matthill8286 I added the logo based on this information this information

<img width="463" alt="Screenshot 2020-12-02 at 12 14 58" src="https://user-images.githubusercontent.com/18351247/100871378-17913e00-3498-11eb-8e28-4512d102b9d0.png">

2020-12-02 12:19 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +}) => {
@matthill8286not sure what you mean, I've looked at other components and they are done in a similar way.

2020-12-02 12:20 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
@philjonasfiltered good point

2020-12-02 12:21 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.story.tsx
> +    icon: '',
@eTheMan80 Well thats wrong as no icon is in the designs. So please remove as we need to adhere to the designs.

2020-12-02 12:21 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +    <div>
@philjonasfiltered yeah you're right, made some last minute changes and forgot to update.

2020-12-02 12:21 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +}) => {
@eTheMan80 Well look at typescript return types, for this it would be `}): JSX.Element => {`

2020-12-02 12:23 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +import * as H from 'history'
@matthill8286 this has been updated

2020-12-02 12:23 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
@matthill8286 this has been updated

2020-12-02 12:23 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +    <div>
@matthill8286 this has been updated

2020-12-02 12:24 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +}) => {
@matthill8286 does this mean that all other components that have been added should have this return type?

2020-12-02 12:26 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +              <Cell key={index} colsLg={1} colsMd={2} colsSm={1} justify="center" align="middle">
@matthill8286 this has been updated

2020-12-02 12:26 UTC, eTheMan80 commented on src/components/Organisms/index.ts
> +export * from './AssetPageFooter'
@matthill8286 this has been updated

2020-12-02 12:27 UTC, philjonasfiltered approved these changes

2020-12-02 12:28 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +          {links &&
@matthill8286 this has been updated

2020-12-02 12:29 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +            ))}
@matthill8286 this has been updated

2020-12-02 12:30 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +    <div>
@philjonasfiltered this has been updated

2020-12-02 12:30 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.interface.ts
> +  links?: { url: string; icon: string; text: string }[]
@philjonasfiltered this has been updated

2020-12-02 12:33 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.story.tsx
> +    icon: '',
@matthill8286 this has been updated

2020-12-02 12:33 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.test.tsx
> +            icon: '',
@matthill8286 this has been updated

2020-12-02 12:33 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +          {links &&
@matthill8286 this has been updated

2020-12-02 12:34 UTC, matthill8286 commented
@eTheMan80 The component looks a bit strange from the screenshot, really you should be using the logo as flex-start with minimal left padding || left margin so it uses up the space and the `powered by...` text should be flex-end and again minimal right padding || right margin so it uses up the space as it looks really squashed together. It also looks like the links aren't centered, they are off to the left.

2020-12-02 13:19 UTC, eTheMan80 commented
@matthill8286 @tricaalexandru do we have an idea on the number of link items we want to have in the navigation? Using the grid it's quite tricky to get the links centered if there are an odd number of items. @matthill8286 I didn't include any extra margin or padding because I assumed that the `<cell>` within the grid would take care of that.

Here's what the footer looks like with 4 link items

<img width="1440" alt="Screenshot 2020-12-02 at 13 00 59" src="https://user-images.githubusercontent.com/18351247/100877620-f123d080-34a0-11eb-8e8b-bcddc250d103.png">

<img width="1011" alt="Screenshot 2020-12-02 at 13 15 18" src="https://user-images.githubusercontent.com/18351247/100877678-0698fa80-34a1-11eb-8af1-b244d0f85e20.png">

2020-12-02 14:56 UTC, tricaalexandru commented
@eTheMan80 the number of links will vary. That is to be configured through the graphCMS

2020-12-02 14:57 UTC, tricaalexandru approved these changes

2020-12-02 15:30 UTC, eTheMan80 commented
@tricaalexandru @matthill8286 I've updated the footer to use the `FlexBox` component, this made more sense. @matthill8286 let me know if this is ok.

<img width="1552" alt="Screenshot 2020-12-02 at 15 26 00" src="https://user-images.githubusercontent.com/18351247/100893427-45d04700-34b3-11eb-90b3-741493c559d9.png">

2020-12-02 16:41 UTC, matthill8286 approved these changes

2020-12-02 16:45 UTC, matthill8286 commented
@eTheMan80 @tricaalexandru perhaps put the right hand text on 2 lines, that might free up some space. I'm not saying you did add extra I'm saying remove the padding or margin to get the left and right components closer to the edge of the parent container. It's pretty simple really. What does it look like on mobile/tablet.

2020-12-03 08:36 UTC, tricaalexandru commented
@eTheMan80 @matthill8286 this now looks way better to me.

2020-12-03 08:36 UTC, tricaalexandru commented
@eTheMan80 there are some new conflicts you need to fix

2020-12-03 08:56 UTC, matthill8286 commented
@eTheMan80 Please update your branch with master

2020-12-04 23:50 UTC, merged