fix: [MAG-000] added globe button
excelWithBusiness/TS-Filtered-SC-Components pull request #58
Opened 2020-12-07 16:22 UTC by philjonasfiltered

# <JIRA issue / Title>

## TL;DR

-   List
-   The
-   Core
-   Changes

## Details

Checklist / Reminders:

-   [ ] Documentation / Story is created / adapted
-   [ ] Unit tests
-   [ ] CSS changes are BEM-compliant

2020-12-07 17:28 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +          )}
I'd suggest to just pass the actual icon in thats required instead of toggling between them.

```suggestion
            <StyledIcon width={16} height={16} rotate={0}>
              {svgIcon}
            </StyledIcon>
```

2020-12-07 17:28 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +    icon,
```suggestion
    svgIcon,
```

2020-12-07 17:28 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  icon?: React.ReactElement
```suggestion
  svgIcon?: React.ReactElement
```

2020-12-07 17:28 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +            {icon ? icon : <SvgEdit />}
```suggestion
            {svgIcon}
```

2020-12-07 17:28 UTC, matthill8286 commented on src/components/Molecules/LanguageDropDown/LanguageDropdown.tsx
> +      icon={<SvgGlobe />}
```suggestion
      svgIcon={<SvgGlobe />}
```

2020-12-08 11:02 UTC, tricaalexandru commented
@philjonasfiltered there's a bit of a mismatch with the design. All in all is good, but here are the necessary changes

1. In the deisgne it's leaning to the left, in yours it's leaning to the right
2. There's a check mark for the current langauge
3. The hilight is of the entire cell, not changing the text of the value



<img width="269" alt="Screenshot 2020-12-08 at 13 00 26" src="https://user-images.githubusercontent.com/7725343/101475669-5a9a5800-3955-11eb-841a-091c1d0e8c3e.png">

2020-12-08 11:02 UTC, tricaalexandru requested changes
@philjonasfiltered left comment in regards to the design

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  isIconTightlyWrapped?: boolean
@philjonasfiltered I'm not sure what this prop is doing, perhaps explain and we can come up with a name that means what it's doing, it might be we could find a solution where we do not need this kind of thing.

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +            height={16}
@philjonasfiltered If all icons in the designs are 16 x 16 then perhaps set that as a default value in the <Icon /> itself.

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +            rotate={iconRotate !== undefined ? iconRotate : showDropdown ? 270 : 90}>
@philjonasfiltered Why not set iconRotate = false as a default, then you could do `iconRotate : showDropdown ? 270 : 90`

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +            isIconTightlyWrapped={isLanguageDropdown}>
```suggestion
            iconLeft={isLanguageDropdown}>
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +    ${isIconTightlyWrapped ? `left: 20%` : `right:  20px`};
```suggestion
    ${iconLeft ? `left: 20%` : `right:  20px`};
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  isIconTightlyWrapped?: boolean
```suggestion
  iconLeft?: boolean
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  isIconTightlyWrapped?: boolean
```suggestion
  iconLeft?: boolean
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  hasCheckmark?: boolean
```suggestion
  checkmark?: boolean
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +    display: ${hasCheckmark ? `inline-flex` : `block`};
```suggestion
    display: ${checkmark ? `inline-flex` : `block`};
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +  ${({ theme, hasCheckmark, active }) => `
```suggestion
  ${({ theme, checkmark, active }) => `
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +    isIconTightlyWrapped,
```suggestion
    iconLeft,
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +  const isLanguageDropdown = iconRotate === 0
@philjonasfiltered What happens if another dropdown uses a icon thats at 0??

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +          {isSelectDisplayed && currentIndex !== -1 && (
```suggestion
          {isOptionValueDisplayed && currentIndex !== -1 && (
```

2020-12-08 13:10 UTC, matthill8286 commented on src/components/Molecules/Dropdown/Dropdown.tsx
> +                hasCheckmark={isLanguageDropdown}
```suggestion
                checkmark={isLanguageDropdown}
```

2020-12-08 13:52 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  isIconTightlyWrapped?: boolean
This makes the container wrap the icon without any dead space to the left.

2020-12-08 14:13 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +    ${isIconTightlyWrapped ? `` : `max-width: 100%;`}
this is breaking the tests

2020-12-08 14:13 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +    ${isIconTightlyWrapped ? `right: 0;` : ``}
this is breaking the tests

2020-12-08 14:14 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.styled.ts
> +    ${hasCheckmark && !active ? `padding-left: 45px;` : ``}
also breaking the tests. I need to figure out why...

2020-12-08 14:18 UTC, philjonasfiltered commented on src/components/Molecules/Dropdown/Dropdown.interface.tsx
> +  isIconTightlyWrapped?: boolean
@matthill8286 makes sense. Up until yesterday, this was a regular dropdown. Now with this new design, it's very far from what other dropdown look like. This is a zero-point task becoming a time sink 😞

2020-12-08 15:15 UTC, tricaalexandru commented
@philjonasfiltered it's way close but still needs a bit of love. 
https://projects.invisionapp.com/share/BUZB2DJGXCW#/screens/436779856

Missing:
1. The up/down arrow
2. Yours doesn't blend with the background (not sure if this matters. Maybe revisit when we have the header finalise)
3. Text is centered differently (@matthill8286 your call. Not sure how much it matters)
4. The scroll bar on right side.

2020-12-08 15:31 UTC, matthill8286 commented
> @philjonasfiltered it's way close but still needs a bit of love.
> https://projects.invisionapp.com/share/BUZB2DJGXCW#/screens/436779856
> 
> Missing:
> 
> 1. The up/down arrow
> 2. Yours doesn't blend with the background (not sure if this matters. Maybe revisit when we have the header finalise)
> 3. Text is centered differently (@matthill8286 your call. Not sure how much it matters)
> 4. The scroll bar on right side.

@tricaalexandru I'll check out the branch and run through it 👍

2020-12-11 09:28 UTC, tricaalexandru commented
@philjonasfiltered so Phil Cowans said we'll have a design review by Craig when the code is done. So we have to make it look identical to the design. I can still see some differences:

1, Either the arrow is too big or the globe is to small
2. The globe and arrow look Bolded
3. The box with the language has rounded corners
4. There is a space above the first item
5. The check icon should be smaller
6. The actual width should be bigger, but honestly I like your version better so let's go with that and see if Craig rejects it. 

@matthill8286 just FYI

2020-12-11 16:36 UTC, philjonasfiltered commented
> @philjonasfiltered so Phil Cowans said we'll have a design review by Craig when the code is done. So we have to make it look identical to the design. I can still see some differences:
> 
> 1, Either the arrow is too big or the globe is to small
Changed Globe size and icon
> 2. The globe and arrow look Bolded
Same as above
> 3. The box with the language has rounded corners
The design has square corners at the top and rounded at the bottom. I updated the component accordingly
> 4. There is a space above the first item
Removed the space
> 5. The check icon should be smaller
Check icon is smaller
> 6. The actual width should be bigger, but honestly I like your version better so let's go with that and see if Craig rejects it.
didn't change that 😄 
> @matthill8286 just FYI

2020-12-16 08:31 UTC, tricaalexandru commented
@philjonasfiltered what's the state of this?

2020-12-16 09:02 UTC, philjonasfiltered commented
> @philjonasfiltered what's the state of this?

If you and @matthill8286 are happy with it, I think it can be merged. If later we need adjustments I can always pick this work again.

2020-12-16 09:58 UTC, matthill8286 commented
@tricaalexandru @philjonasfiltered agreed we can always revisit it if it needs it, don't see the value of any more time on such a small thing

2020-12-16 09:58 UTC, matthill8286 approved these changes

2020-12-16 09:59 UTC, merged