chore(ui refactor bugs): [MAG-3119] updated onboarding button component with optional prop and made asset page footer responsive
excelWithBusiness/TS-Filtered-SC-Components pull request #72
Opened 2020-12-14 18:05 UTC by eTheMan80

# <MAG-3119 / Build the Footer organism>

## TL;DR

-   List
-   The
-   Core
-   Changes

## Details

Checklist / Reminders:

-   [x] Documentation / Story is created / adapted
-   [ ] Unit tests
-   [ ] CSS changes are BEM-compliant

<img width="1552" alt="Screenshot 2020-12-14 at 17 43 07" src="https://user-images.githubusercontent.com/18351247/102117905-d3f2e880-3e36-11eb-8162-5bad7004f7bc.png">
<img width="1552" alt="Screenshot 2020-12-14 at 17 44 25" src="https://user-images.githubusercontent.com/18351247/102117903-d35a5200-3e36-11eb-89fa-859f5e06ac0c.png">
<img width="1552" alt="Screenshot 2020-12-14 at 17 44 43" src="https://user-images.githubusercontent.com/18351247/102117884-cfc6cb00-3e36-11eb-968d-d749df6bf032.png">

2020-12-14 18:27 UTC, tricaalexandru approved these changes

2020-12-15 09:03 UTC, philjonasfiltered approved these changes

2020-12-16 06:10 UTC, matthill8286 approved these changes

2020-12-16 06:10 UTC, matthill8286 commented on src/components/Molecules/OnboardingButton/OnboardingButton.interface.ts
> +  onboardingClick?: (ev: React.MouseEvent<HTMLElement>) => void
This button for the feature requires a click handler 
The `to:?` can stay as it's definitely optional :)

```suggestion
  onboardingClick: (ev: React.MouseEvent<HTMLElement>) => void
```

2020-12-16 06:10 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
It is space you're struggling with?? Why not make the font size, paddings/margins smaller for tablet/mobile, check out `Exposed.md` under `Media Queries`

2020-12-16 06:10 UTC, matthill8286 commented on src/components/Molecules/OnboardingButton/OnboardingButton.story.tsx
> +      <OnboardingButton actionType={'ghost'} onboardingClick={action('click')}>
add `onboardingClick={}` to all tests as well

2020-12-16 08:11 UTC, tricaalexandru commented
@eTheMan80 is this mergeable?

2020-12-16 08:14 UTC, tricaalexandru commented
@eTheMan80 have you acted upon the reviews

2020-12-16 10:05 UTC, eTheMan80 commented
@tricaalexandru I'll implement the reviews now, just updated a previous pr that's ready for review.

2020-12-16 11:39 UTC, tricaalexandru commented
@eTheMan80 let me know when that's done please.

2020-12-16 13:00 UTC, tricaalexandru commented
@eTheMan80 updates?

2020-12-16 16:27 UTC, eTheMan80 commented on src/components/Molecules/OnboardingButton/OnboardingButton.story.tsx
> +      <OnboardingButton actionType={'ghost'} onboardingClick={action('click')}>
@matthill8286 this has been updated

2020-12-16 16:28 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
@matthill8286 I'm not sure if this is what you meant..!

2020-12-16 16:29 UTC, eTheMan80 commented
@tricaalexandru Sorry I've had brain freeze today. I've done an update but need @matthill8286 to have a look.

2020-12-16 17:56 UTC, matthill8286 commented
@eTheMan80 Could you just attach tablet and mobile screenshots please then I can validate and it should be good to go.

2020-12-16 19:14 UTC, matthill8286 commented
@eTheMan80 it seems broken on tablet??

2020-12-16 19:22 UTC, matthill8286 requested changes

2020-12-16 19:22 UTC, matthill8286 commented on src/components/Helper/FlexBox/FlexBox.tsx
> +  }
@tricaalexandru @eTheMan80 you need to adjust these values in your AssetPageFooter component and not directly on the FlexBox itself as this will change for all components that use FlexBox.

2020-12-16 19:22 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
ok, how about lets just set them to 

```
<Cell columns={6} colsMd={12} colsSm={12} justify="center" align="middle">

2020-12-16 19:22 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={3} colsLg={4} colsMd={8} colsSm={8} justify="center" align="middle">
```suggestion
      <Cell columns={6} colsMd={12} colsSm={12} justify="center" align="middle">
```

2020-12-16 19:22 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={3} colsLg={2} colsMd={3} colsSm={8} justify="center" align="middle">
```suggestion
      <Cell columns={6} colsMd={12} colsSm={12} justify="center" align="middle">
```

2020-12-17 08:51 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
@matthill8286 if I update these props to `colsMd={12} colsSm={12}` I get the warning below?

<img width="696" alt="Screenshot 2020-12-17 at 08 49 59" src="https://user-images.githubusercontent.com/18351247/102464900-e17dbd80-4044-11eb-9901-6c5dbe25aad4.png">
<img width="696" alt="Screenshot 2020-12-17 at 08 48 24" src="https://user-images.githubusercontent.com/18351247/102464904-e3e01780-4044-11eb-991d-077a160372c8.png">

2020-12-17 08:55 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={3} colsLg={4} colsMd={8} colsSm={8} justify="center" align="middle">
@matthill8286 I don't think `columns={6}` will work for the copy text on desktop, it will make the display look awkward.

2020-12-17 08:56 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={3} colsLg={2} colsMd={3} colsSm={8} justify="center" align="middle">
@matthill8286 same as above with the screenshot

2020-12-17 09:03 UTC, eTheMan80 commented on src/components/Helper/FlexBox/FlexBox.tsx
> +  }
@matthill8286 do you mean adding a prop in AssetPageFooter that will control the padding on FlexBox?

2020-12-17 09:13 UTC, matthill8286 commented
so <Cell columns={4} colsMd={8} colsSm={8}  align="middle"> is the answer, you will just need to control justify of the `<Cell />` for Desktop, you can use justifyContent: center for tablet and mobile so look at how the styled-components are used to extend an Atom, the syntax is like this: `const StyledCell = styled(Cell).....`

![Screenshot 2020-12-17 at 11 09 17](https://user-images.githubusercontent.com/48310431/102467009-73db8c80-4058-11eb-916e-c976936f5374.png)

2020-12-17 09:14 UTC, matthill8286 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
@eTheMan80 `<Cell columns={4} colsMd={8} colsSm={8} justify="center" align="middle">`

2020-12-17 10:27 UTC, eTheMan80 commented on src/components/Organisms/AssetPageFooter/AssetPageFooter.tsx
> +      <Cell colsXl={6} colsLg={6} colsMd={5} colsSm={8} justify="center" align="middle">
@matthill8286 I've updated the cell to `<Cell columns={4} colsMd={4} colsSm={8} align="middle">`

2020-12-17 10:27 UTC, eTheMan80 commented
@matthill8286 @tricaalexandru I've updated the pr

<img width="704" alt="Screenshot 2020-12-17 at 10 23 41" src="https://user-images.githubusercontent.com/18351247/102475715-22300380-4052-11eb-8293-53404e5a3d71.png">
<img width="1552" alt="Screenshot 2020-12-17 at 10 23 24" src="https://user-images.githubusercontent.com/18351247/102475735-2a883e80-4052-11eb-943e-08753d62e028.png">
<img width="885" alt="Screenshot 2020-12-17 at 10 23 36" src="https://user-images.githubusercontent.com/18351247/102475730-28be7b00-4052-11eb-9ecc-0962e08bab5b.png">

2020-12-18 11:39 UTC, matthill8286 approved these changes

2020-12-18 12:28 UTC, tricaalexandru approved these changes

2020-12-18 14:03 UTC, merged